import { ICandidate } from "./Candidate";
import { ICustomer } from "./Customer";
import { IOpportunity } from "./Opportunity";
import { IPosition } from "./Position";

const generateFakeData = (): {
  candidates: ICandidate[];
  customers: ICustomer[];
} => {
  const firstNames = [
    "John",
    "William",
    "James",
    "Charles",
    "George",
    "Frank",
    "Joseph",
    "Thomas",
    "Henry",
    "Robert",
    "Edward",
    "Harry",
    "Walter",
    "Arthur",
    "Fred",
    "Albert",
    "Samuel",
    "David",
    "Louis",
    "Joe",
    "Charlie",
    "Clarence",
    "Richard",
    "Andrew",
    "Daniel",
    "Ernest",
    "Will",
    "Jesse",
    "Oscar",
    "Lewis",
    "Peter",
    "Benjamin",
    "Frederick",
    "Willie",
    "Alfred",
    "Sam",
    "Roy",
    "Herbert",
    "Jacob",
    "Tom",
    "Elmer",
    "Carl",
    "Lee",
    "Howard",
    "Martin",
    "Michael",
    "Bert",
    "Herman",
    "Jim",
    "Francis",
    "Harvey",
    "Earl",
    "Eugene",
    "Ralph",
    "Ed",
    "Claude",
    "Edwin",
    "Ben",
    "Charley",
    "Paul",
    "Edgar",
    "Isaac",
    "Otto",
    "Luther",
    "Lawrence",
    "Ira",
    "Patrick",
    "Guy",
    "Oliver",
    "Theodore",
    "Hugh",
    "Clyde",
    "Alexander",
    "August",
    "Floyd",
    "Homer",
    "Jack",
    "Leonard",
    "Horace",
    "Marion",
    "Philip",
    "Allen",
    "Archie",
    "Stephen",
    "Chester",
    "Willis",
    "Raymond",
    "Rufus",
    "Warren",
    "Jessie",
    "Milton",
    "Alex",
    "Leo",
    "Julius",
    "Ray",
    "Sidney",
    "Bernard",
    "Dan",
    "Jerry",
    "Calvin",
    "Perry",
    "Dave",
    "Anthony",
    "Eddie",
    "Amos",
    "Dennis",
    "Clifford",
    "Leroy",
    "Wesley",
    "Alonzo",
    "Garfield",
    "Franklin",
    "Emil",
    "Leon",
    "Nathan",
    "Harold",
    "Matthew",
    "Levi",
    "Moses",
    "Everett",
    "Lester",
    "Winfield",
    "Adam",
    "Lloyd",
    "Mack",
    "Fredrick",
    "Jay",
    "Jess",
    "Melvin",
    "Noah",
    "Aaron",
    "Alvin",
    "Norman",
    "Gilbert",
    "Elijah",
    "Victor",
    "Gus",
    "Nelson",
    "Jasper",
    "Silas",
    "Jake",
    "Christopher",
    "Mike",
    "Percy",
    "Adolph",
    "Maurice",
    "Cornelius",
    "Felix",
    "Reuben",
    "Wallace",
    "Claud",
    "Roscoe",
    "Sylvester",
    "Earnest",
    "Hiram",
    "Otis",
    "Simon",
    "Willard",
    "Irvin",
    "Mark",
    "Jose",
    "Wilbur",
    "Abraham",
    "Virgil",
    "Clinton",
    "Elbert",
    "Leslie",
    "Marshall",
    "Owen",
    "Wiley",
    "Anton",
    "Morris",
    "Manuel",
    "Phillip",
    "Augustus",
    "Emmett",
    "Eli",
    "Nicholas",
    "Wilson",
    "Alva",
    "Harley",
    "Newton",
    "Timothy",
    "Marvin",
    "Ross",
    "Curtis",
    "Edmund",
    "Jeff",
    "Elias",
    "Harrison",
    "Stanley",
    "Columbus",
    "Lon",
    "Ora",
    "Ollie",
    "Pearl",
    "Russell",
    "Solomon",
    "Arch",
    "Asa",
    "Clayton",
    "Enoch",
    "Irving",
    "Mathew",
    "Nathaniel",
    "Scott",
    "Hubert",
    "Lemuel",
    "Andy",
    "Ellis",
    "Emanuel",
    "Joshua",
    "Millard",
    "Vernon",
    "Wade",
    "Cyrus",
    "Miles",
    "Rudolph",
    "Sherman",
    "Austin",
    "Bill",
    "Chas",
    "Lonnie",
    "Monroe",
    "Byron",
    "Edd",
    "Emery",
    "Grant",
    "Jerome",
    "Max",
    "Mose",
    "Steve",
    "Gordon",
    "Abe",
    "Pete",
    "Chris",
    "Clark",
    "Gustave",
    "Orville",
    "Lorenzo",
    "Bruce",
    "Marcus",
    "Preston",
    "Bob",
    "Dock",
    "Donald",
    "Jackson",
    "Cecil",
    "Barney",
    "Delbert",
    "Edmond",
    "Anderson",
    "Christian",
    "Glenn",
    "Jefferson",
    "Luke",
    "Neal",
    "Burt",
    "Ike",
    "Myron",
    "Tony",
    "Conrad",
    "Joel",
    "Matt",
    "Riley",
    "Vincent",
    "Emory",
    "Isaiah",
    "Nick",
    "Ezra",
    "Green",
    "Juan",
    "Clifton",
    "Lucius",
    "Porter",
    "Arnold",
    "Bud",
    "Jeremiah",
    "Taylor",
    "Forrest",
    "Roland",
    "Spencer",
    "Burton",
    "Don",
    "Emmet",
    "Gustav",
    "Louie",
    "Morgan",
    "Ned",
    "Van",
    "Ambrose",
    "Chauncey",
    "Elisha",
    "Ferdinand",
    "General",
    "Julian",
    "Kenneth",
    "Mitchell",
    "Allie",
    "Josh",
    "Judson",
    "Lyman",
    "Napoleon",
    "Pedro",
    "Berry",
    "Dewitt",
    "Ervin",
    "Forest",
    "Lynn",
    "Pink",
    "Ruben",
    "Sanford",
    "Ward",
    "Douglas",
    "Ole",
    "Omer",
    "Ulysses",
    "Walker",
    "Wilbert",
    "Adelbert",
    "Benjiman",
    "Ivan",
    "Jonas",
    "Major",
    "Abner",
    "Archibald",
    "Caleb",
    "Clint",
    "Dudley",
    "Granville",
    "King",
    "Mary",
    "Merton",
    "Antonio",
    "Bennie",
    "Carroll",
    "Freeman",
    "Josiah",
    "Milo",
    "Royal",
    "Dick",
    "Earle",
    "Elza",
    "Emerson",
    "Fletcher",
    "Judge",
    "Laurence",
    "Neil",
    "Roger",
    "Seth",
    "Glen",
    "Hugo",
    "Jimmie",
    "Johnnie",
    "Washington",
    "Elwood",
    "Gust",
    "Harmon",
    "Jordan",
    "Simeon",
    "Wayne",
    "Wilber",
    "Clem",
    "Evan",
    "Frederic",
    "Irwin",
    "Junius",
    "Lafayette",
    "Loren",
    "Madison",
    "Mason",
    "Orval",
    "Abram",
    "Aubrey",
    "Elliott",
    "Hans",
    "Karl",
    "Minor",
    "Wash",
    "Wilfred",
    "Allan",
    "Alphonse",
    "Dallas",
    "Dee",
    "Isiah",
    "Jason",
    "Johnny",
    "Lawson",
    "Lew",
    "Micheal",
    "Orin",
    "Addison",
    "Cal",
    "Erastus",
    "Francisco",
    "Hardy",
    "Lucien",
    "Randolph",
    "Stewart",
    "Vern",
    "Wilmer",
    "Zack",
    "Adrian",
    "Alvah",
    "Bertram",
    "Clay",
    "Ephraim",
    "Fritz",
    "Giles",
    "Grover",
    "Harris",
    "Isom",
    "Jesus",
    "Johnie",
    "Jonathan",
    "Lucian",
    "Malcolm",
    "Merritt",
    "Otho",
    "Perley",
    "Rolla",
    "Sandy",
    "Tomas",
    "Wilford",
    "Adolphus",
    "Angus",
    "Arther",
    "Carlos",
    "Cary",
    "Cassius",
    "Davis",
    "Hamilton",
    "Harve",
    "Israel",
    "Leander",
    "Melville",
    "Merle",
    "Murray",
    "Pleasant",
    "Sterling",
    "Steven",
    "Axel",
    "Boyd",
    "Bryant",
    "Clement",
    "Erwin",
    "Ezekiel",
    "Foster",
    "Frances",
    "Geo",
    "Houston",
    "Issac",
    "Jules",
    "Larkin",
    "Mat",
    "Morton",
    "Orlando",
    "Pierce",
    "Prince",
    "Rollie",
    "Rollin",
    "Sim",
    "Stuart",
    "Wilburn",
    "Bennett",
    "Casper",
    "Christ",
    "Dell",
    "Egbert",
    "Elmo",
    "Fay",
    "Gabriel",
    "Hector",
    "Horatio",
    "Lige",
    "Saul",
    "Smith",
    "Squire",
    "Tobe",
    "Tommie",
    "Wyatt",
    "Alford",
    "Alma",
    "Alton",
    "Andres",
    "Burl",
    "Cicero",
    "Dean",
    "Dorsey",
    "Enos",
    "Howell",
    "Lou",
    "Loyd",
    "Mahlon",
    "Nat",
    "Omar",
    "Oran",
    "Parker",
    "Raleigh",
    "Reginald",
    "Rubin",
    "Seymour",
    "Wm",
    "Young",
    "Benjamine",
    "Carey",
    "Carlton",
    "Eldridge",
    "Elzie",
    "Garrett",
    "Isham",
    "Johnson",
    "Larry",
    "Logan",
    "Merrill",
    "Mont",
    "Oren",
    "Pierre",
    "Rex",
    "Rodney",
    "Ted",
    "Webster",
    "West",
    "Wheeler",
    "Willam",
    "Al",
    "Aloysius",
    "Alvie",
    "Anna",
    "Art",
    "Augustine",
    "Bailey",
    "Benjaman",
    "Beverly",
    "Bishop",
    "Clair",
    "Cloyd",
    "Coleman",
    "Dana",
    "Duncan",
    "Dwight",
    "Emile",
    "Evert",
    "Henderson",
    "Hunter",
    "Jean",
    "Lem",
    "Luis",
    "Mathias",
    "Maynard",
    "Miguel",
    "Mortimer",
    "Nels",
    "Norris",
    "Pat",
    "Phil",
    "Rush",
    "Santiago",
    "Sol",
    "Sydney",
    "Thaddeus",
    "Thornton",
    "Tim",
    "Travis",
    "Truman",
    "Watson",
    "Webb",
    "Wellington",
    "Winfred",
    "Wylie",
    "Alec",
    "Basil",
    "Baxter",
    "Bertrand",
    "Buford",
    "Burr",
    "Cleveland",
    "Colonel",
    "Dempsey",
    "Early",
    "Ellsworth",
    "Fate",
    "Finley",
    "Gabe",
    "Garland",
    "Gerald",
    "Herschel",
    "Hezekiah",
    "Justus",
    "Lindsey",
    "Marcellus",
    "Olaf",
    "Olin",
    "Pablo",
    "Rolland",
    "Turner",
    "Verne",
    "Volney",
    "Williams",
    "Almon",
    "Alois",
    "Alonza",
    "Anson",
    "Authur",
    "Benton",
    "Billie",
    "Cornelious",
    "Darius",
    "Denis",
    "Dillard",
    "Doctor",
    "Elvin",
    "Emma",
    "Eric",
    "Evans",
    "Gideon",
    "Haywood",
    "Hilliard",
    "Hosea",
    "Lincoln",
    "Lonzo",
    "Lucious",
    "Lum",
    "Malachi",
    "Newt",
    "Noel",
    "Orie",
    "Palmer",
    "Pinkney",
    "Shirley",
    "Sumner",
    "Terry",
    "Urban",
    "Uriah",
    "Valentine",
    "Waldo",
    "Warner",
    "Wong",
    "Zeb",
    "Abel",
    "Alden",
    "Archer",
    "Avery",
    "Carson",
    "Cullen",
    "Doc",
    "Eben",
    "Elige",
    "Elizabeth",
    "Elmore",
    "Ernst",
    "Finis",
    "Freddie",
    "Godfrey",
    "Guss",
    "Hamp",
    "Hermann",
    "Isadore",
    "Isreal",
    "Jones",
    "June",
    "Lacy",
    "Lafe",
    "Leland",
    "Llewellyn",
    "Ludwig",
    "Manford",
    "Maxwell",
    "Minnie",
    "Obie",
    "Octave",
    "Orrin",
    "Ossie",
    "Oswald",
    "Park",
    "Parley",
    "Ramon",
    "Rice",
    "Stonewall",
    "Theo",
    "Tillman",
    "Addie",
    "Aron",
    "Ashley",
    "Bernhard",
    "Bertie",
    "Berton",
    "Buster",
    "Butler",
    "Carleton",
    "Carrie",
    "Clara",
    "Clarance",
    "Clare",
    "Crawford",
    "Danial",
    "Dayton",
    "Dolphus",
    "Elder",
    "Ephriam",
    "Fayette",
    "Felipe",
    "Fernando",
    "Flem",
    "Florence",
    "Ford",
    "Harlan",
    "Hayes",
    "Henery",
    "Hoy",
    "Huston",
    "Ida",
    "Ivory",
    "Jonah",
    "Justin",
    "Lenard",
    "Leopold",
    "Lionel",
    "Manley",
    "Marquis",
    "Marshal",
    "Mart",
    "Odie",
    "Olen",
    "Oral",
    "Orley",
    "Otha",
    "Press",
    "Price",
    "Quincy",
    "Randall",
    "Rich",
    "Richmond",
    "Romeo",
    "Russel",
    "Rutherford",
    "Shade",
    "Shelby",
    "Solon",
    "Thurman",
    "Tilden",
    "Troy",
    "Woodson",
    "Worth",
    "Aden",
    "Alcide",
    "Alf",
    "Algie",
    "Arlie",
    "Bart",
    "Bedford",
    "Benito",
    "Billy",
    "Bird",
    "Birt",
    "Bruno",
    "Burley",
    "Chancy",
    "Claus",
    "Cliff",
    "Clovis",
    "Connie",
    "Creed",
    "Delos",
    "Duke",
    "Eber",
    "Eligah",
    "Elliot",
    "Elton",
    "Emmitt",
    "Gene",
    "Golden",
    "Hal",
    "Hardin",
    "Harman",
    "Hervey",
    "Hollis",
    "Ivey",
    "Jennie",
    "Len",
    "Lindsay",
    "Lonie",
    "Lyle",
    "Mac",
    "Mal",
    "Math",
    "Miller",
    "Orson",
    "Osborne",
    "Percival",
    "Pleas",
    "Ples",
    "Rafael",
    "Raoul",
    "Roderick",
    "Rose",
    "Shelton",
    "Sid",
    "Theron",
    "Tobias",
    "Toney",
    "Tyler",
    "Vance",
    "Vivian",
    "Walton",
    "Watt",
    "Weaver",
    "Wilton",
    "Adolf",
    "Albin",
    "Albion",
    "Allison",
    "Alpha",
    "Alpheus",
    "Anastacio",
    "Andre",
    "Annie",
    "Arlington",
    "Armand",
    "Asberry",
    "Asbury",
    "Asher",
    "Augustin",
    "Auther",
    "Author",
    "Ballard",
    "Blas",
    "Caesar",
    "Candido",
    "Cato",
    "Clarke",
    "Clemente",
    "Colin",
    "Commodore",
    "Cora",
    "Coy",
    "Cruz",
    "Curt",
    "Damon",
    "Davie",
    "Mary",
    "Anna",
    "Emma",
    "Elizabeth",
    "Minnie",
    "Margaret",
    "Ida",
    "Alice",
    "Bertha",
    "Sarah",
    "Annie",
    "Clara",
    "Ella",
    "Florence",
    "Cora",
    "Martha",
    "Laura",
    "Nellie",
    "Grace",
    "Carrie",
    "Maude",
    "Mabel",
    "Bessie",
    "Jennie",
    "Gertrude",
    "Julia",
    "Hattie",
    "Edith",
    "Mattie",
    "Rose",
    "Catherine",
    "Lillian",
    "Ada",
    "Lillie",
    "Helen",
    "Jessie",
    "Louise",
    "Ethel",
    "Lula",
    "Myrtle",
    "Eva",
    "Frances",
    "Lena",
    "Lucy",
    "Edna",
    "Maggie",
    "Pearl",
    "Daisy",
    "Fannie",
    "Josephine",
    "Dora",
    "Rosa",
    "Katherine",
    "Agnes",
    "Marie",
    "Nora",
    "May",
    "Mamie",
    "Blanche",
    "Stella",
    "Ellen",
    "Nancy",
    "Effie",
    "Sallie",
    "Nettie",
    "Della",
    "Lizzie",
    "Flora",
    "Susie",
    "Maud",
    "Mae",
    "Etta",
    "Harriet",
    "Sadie",
    "Caroline",
    "Katie",
    "Lydia",
    "Elsie",
    "Kate",
    "Susan",
    "Mollie",
    "Alma",
    "Addie",
    "Georgia",
    "Eliza",
    "Lulu",
    "Nannie",
    "Lottie",
    "Amanda",
    "Belle",
    "Charlotte",
    "Rebecca",
    "Ruth",
    "Viola",
    "Olive",
    "Amelia",
    "Hannah",
    "Jane",
    "Virginia",
    "Emily",
    "Matilda",
    "Irene",
    "Kathryn",
    "Esther",
    "Willie",
    "Henrietta",
    "Ollie",
    "Amy",
    "Rachel",
    "Sara",
    "Estella",
    "Theresa",
    "Augusta",
    "Ora",
    "Pauline",
    "Josie",
    "Lola",
    "Sophia",
    "Leona",
    "Anne",
    "Mildred",
    "Ann",
    "Beulah",
    "Callie",
    "Lou",
    "Delia",
    "Eleanor",
    "Barbara",
    "Iva",
    "Louisa",
    "Maria",
    "Mayme",
    "Evelyn",
    "Estelle",
    "Nina",
    "Betty",
    "Marion",
    "Bettie",
    "Dorothy",
    "Luella",
    "Inez",
    "Lela",
    "Rosie",
    "Allie",
    "Millie",
    "Janie",
    "Cornelia",
    "Victoria",
    "Ruby",
    "Winifred",
    "Alta",
    "Celia",
    "Christine",
    "Beatrice",
    "Birdie",
    "Harriett",
    "Mable",
    "Myra",
    "Sophie",
    "Tillie",
    "Isabel",
    "Sylvia",
    "Carolyn",
    "Isabelle",
    "Leila",
    "Sally",
    "Ina",
    "Essie",
    "Bertie",
    "Nell",
    "Alberta",
    "Katharine",
    "Lora",
    "Rena",
    "Mina",
    "Rhoda",
    "Mathilda",
    "Abbie",
    "Eula",
    "Dollie",
    "Hettie",
    "Eunice",
    "Fanny",
    "Ola",
    "Lenora",
    "Adelaide",
    "Christina",
    "Lelia",
    "Nelle",
    "Sue",
    "Johanna",
    "Lilly",
    "Lucinda",
    "Minerva",
    "Lettie",
    "Roxie",
    "Cynthia",
    "Helena",
    "Hilda"
  ];
  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Miller",
    "Davis",
    "Garcia",
    "Rodriguez",
    "Wilson",
    "Martinez",
    "Anderson",
    "Taylor",
    "Thomas",
    "Hernandez",
    "Moore",
    "Martin",
    "Jackson",
    "Thompson",
    "White",
    "Lopez",
    "Lee",
    "Gonzalez",
    "Harris",
    "Clark",
    "Lewis",
    "Robinson",
    "Walker",
    "Perez",
    "Hall",
    "Young",
    "Allen",
    "Sanchez",
    "Wright",
    "King",
    "Scott",
    "Green",
    "Baker",
    "Adams",
    "Nelson",
    "Hill",
    "Ramirez",
    "Campbell",
    "Mitchell",
    "Roberts",
    "Carter",
    "Phillips",
    "Evans",
    "Turner",
    "Torres",
    "Parker",
    "Collins",
    "Edwards",
    "Stewart",
    "Flores",
    "Morris",
    "Nguyen",
    "Murphy",
    "Rivera",
    "Cook",
    "Rogers",
    "Morgan",
    "Peterson",
    "Cooper",
    "Reed",
    "Bailey",
    "Bell",
    "Gomez",
    "Kelly",
    "Howard",
    "Ward",
    "Cox",
    "Diaz",
    "Richardson",
    "Wood",
    "Watson",
    "Brooks",
    "Bennett",
    "Gray",
    "James",
    "Reyes",
    "Cruz",
    "Hughes",
    "Price",
    "Myers",
    "Long",
    "Foster",
    "Sanders",
    "Ross",
    "Morales",
    "Powell",
    "Sullivan",
    "Russell",
    "Ortiz",
    "Jenkins",
    "Gutierrez",
    "Perry",
    "Butler",
    "Barnes",
    "Fisher",
    "Henderson",
    "Coleman",
    "Simmons",
    "Patterson",
    "Jordan",
    "Reynolds",
    "Hamilton",
    "Graham",
    "Kim",
    "Gonzales",
    "Alexander",
    "Ramos",
    "Wallace",
    "Griffin",
    "West",
    "Cole",
    "Hayes",
    "Chavez",
    "Gibson",
    "Bryant",
    "Ellis",
    "Stevens",
    "Murray",
    "Ford",
    "Marshall",
    "Owens",
    "Mcdonald",
    "Harrison",
    "Ruiz",
    "Kennedy",
    "Wells",
    "Alvarez",
    "Woods",
    "Mendoza",
    "Castillo",
    "Olson",
    "Webb",
    "Washington",
    "Tucker",
    "Freeman",
    "Burns",
    "Henry",
    "Vasquez",
    "Snyder",
    "Simpson",
    "Crawford",
    "Jimenez",
    "Porter",
    "Mason",
    "Shaw",
    "Gordon",
    "Wagner",
    "Hunter",
    "Romero",
    "Hicks",
    "Dixon",
    "Hunt",
    "Palmer",
    "Robertson",
    "Black",
    "Holmes",
    "Stone",
    "Meyer",
    "Boyd",
    "Mills",
    "Warren",
    "Fox",
    "Rose",
    "Rice",
    "Moreno",
    "Schmidt",
    "Patel",
    "Ferguson",
    "Nichols",
    "Herrera",
    "Medina",
    "Ryan",
    "Fernandez",
    "Weaver",
    "Daniels",
    "Stephens",
    "Gardner",
    "Payne",
    "Kelley",
    "Dunn",
    "Pierce",
    "Arnold",
    "Tran",
    "Spencer",
    "Peters",
    "Hawkins",
    "Grant",
    "Hansen",
    "Castro",
    "Hoffman",
    "Hart",
    "Elliott",
    "Cunningham",
    "Knight",
    "Bradley",
    "Carroll",
    "Hudson",
    "Duncan",
    "Armstrong",
    "Berry",
    "Andrews",
    "Johnston",
    "Ray",
    "Lane",
    "Riley",
    "Carpenter",
    "Perkins",
    "Aguilar",
    "Silva",
    "Richards",
    "Willis",
    "Matthews",
    "Chapman",
    "Lawrence",
    "Garza",
    "Vargas",
    "Watkins",
    "Wheeler",
    "Larson",
    "Carlson",
    "Harper",
    "George",
    "Greene",
    "Burke",
    "Guzman",
    "Morrison",
    "Munoz",
    "Jacobs",
    "Obrien",
    "Lawson",
    "Franklin",
    "Lynch",
    "Bishop",
    "Carr",
    "Salazar",
    "Austin",
    "Mendez",
    "Gilbert",
    "Jensen",
    "Williamson",
    "Montgomery",
    "Harvey",
    "Oliver",
    "Howell",
    "Dean",
    "Hanson",
    "Weber",
    "Garrett",
    "Sims",
    "Burton",
    "Fuller",
    "Soto",
    "Mccoy",
    "Welch",
    "Chen",
    "Schultz",
    "Walters",
    "Reid",
    "Fields",
    "Walsh",
    "Little",
    "Fowler",
    "Bowman",
    "Davidson",
    "May",
    "Day",
    "Schneider",
    "Newman",
    "Brewer",
    "Lucas",
    "Holland",
    "Wong",
    "Banks",
    "Santos",
    "Curtis",
    "Pearson",
    "Delgado",
    "Valdez",
    "Pena",
    "Rios",
    "Douglas",
    "Sandoval",
    "Barrett",
    "Hopkins",
    "Keller",
    "Guerrero",
    "Stanley",
    "Bates",
    "Alvarado",
    "Beck",
    "Ortega",
    "Wade",
    "Estrada",
    "Contreras",
    "Barnett",
    "Caldwell",
    "Santiago",
    "Lambert",
    "Powers",
    "Chambers",
    "Nunez",
    "Craig",
    "Leonard",
    "Lowe",
    "Rhodes",
    "Byrd",
    "Gregory",
    "Shelton",
    "Frazier",
    "Becker",
    "Maldonado",
    "Fleming",
    "Vega",
    "Sutton",
    "Cohen",
    "Jennings",
    "Parks",
    "Mcdaniel",
    "Watts",
    "Barker",
    "Norris",
    "Vaughn",
    "Vazquez",
    "Holt",
    "Schwartz",
    "Steele",
    "Benson",
    "Neal",
    "Dominguez",
    "Horton",
    "Terry",
    "Wolfe",
    "Hale",
    "Lyons",
    "Graves",
    "Haynes",
    "Miles",
    "Park",
    "Warner",
    "Padilla",
    "Bush",
    "Thornton",
    "Mccarthy",
    "Mann",
    "Zimmerman",
    "Erickson",
    "Fletcher",
    "Mckinney",
    "Page",
    "Dawson",
    "Joseph",
    "Marquez",
    "Reeves",
    "Klein",
    "Espinoza",
    "Baldwin",
    "Moran",
    "Love",
    "Robbins",
    "Higgins",
    "Ball",
    "Cortez",
    "Le",
    "Griffith",
    "Bowen",
    "Sharp",
    "Cummings",
    "Ramsey",
    "Hardy",
    "Swanson",
    "Barber",
    "Acosta",
    "Luna",
    "Chandler",
    "Blair",
    "Daniel",
    "Cross",
    "Simon",
    "Dennis",
    "Oconnor",
    "Quinn",
    "Gross",
    "Navarro",
    "Moss",
    "Fitzgerald",
    "Doyle",
    "Mclaughlin",
    "Rojas",
    "Rodgers",
    "Stevenson",
    "Singh",
    "Yang",
    "Figueroa",
    "Harmon",
    "Newton",
    "Paul",
    "Manning",
    "Garner",
    "Mcgee",
    "Reese",
    "Francis",
    "Burgess",
    "Adkins",
    "Goodman",
    "Curry",
    "Brady",
    "Christensen",
    "Potter",
    "Walton",
    "Goodwin",
    "Mullins",
    "Molina",
    "Webster",
    "Fischer",
    "Campos",
    "Avila",
    "Sherman",
    "Todd",
    "Chang",
    "Blake",
    "Malone",
    "Wolf",
    "Hodges",
    "Juarez",
    "Gill",
    "Farmer",
    "Hines",
    "Gallagher",
    "Duran",
    "Hubbard",
    "Cannon",
    "Miranda",
    "Wang",
    "Saunders",
    "Tate",
    "Mack",
    "Hammond",
    "Carrillo",
    "Townsend",
    "Wise",
    "Ingram",
    "Barton",
    "Mejia",
    "Ayala",
    "Schroeder",
    "Hampton",
    "Rowe",
    "Parsons",
    "Frank",
    "Waters",
    "Strickland",
    "Osborne",
    "Maxwell",
    "Chan",
    "Deleon",
    "Norman",
    "Harrington",
    "Casey",
    "Patton",
    "Logan",
    "Bowers",
    "Mueller",
    "Glover",
    "Floyd",
    "Hartman",
    "Buchanan",
    "Cobb",
    "French",
    "Kramer",
    "Mccormick",
    "Clarke",
    "Tyler",
    "Gibbs",
    "Moody",
    "Conner",
    "Sparks",
    "Mcguire",
    "Leon",
    "Bauer",
    "Norton",
    "Pope",
    "Flynn",
    "Hogan",
    "Robles",
    "Salinas",
    "Yates",
    "Lindsey",
    "Lloyd",
    "Marsh",
    "Mcbride",
    "Owen",
    "Solis",
    "Pham",
    "Lang",
    "Pratt",
    "Lara",
    "Brock",
    "Ballard",
    "Trujillo",
    "Shaffer",
    "Drake",
    "Roman",
    "Aguirre",
    "Morton",
    "Stokes",
    "Lamb",
    "Pacheco",
    "Patrick",
    "Cochran",
    "Shepherd",
    "Cain",
    "Burnett",
    "Hess",
    "Li",
    "Cervantes",
    "Olsen",
    "Briggs",
    "Ochoa",
    "Cabrera",
    "Velasquez",
    "Montoya",
    "Roth",
    "Meyers",
    "Cardenas",
    "Fuentes",
    "Weiss",
    "Hoover",
    "Wilkins",
    "Nicholson",
    "Underwood",
    "Short",
    "Carson",
    "Morrow",
    "Colon",
    "Holloway",
    "Summers",
    "Bryan",
    "Petersen",
    "Mckenzie",
    "Serrano",
    "Wilcox",
    "Carey",
    "Clayton",
    "Poole",
    "Calderon",
    "Gallegos",
    "Greer",
    "Rivas",
    "Guerra",
    "Decker",
    "Collier",
    "Wall",
    "Whitaker",
    "Bass",
    "Flowers",
    "Davenport",
    "Conley",
    "Houston",
    "Huff",
    "Copeland",
    "Hood",
    "Monroe",
    "Massey",
    "Roberson",
    "Combs",
    "Franco",
    "Larsen",
    "Pittman",
    "Randall",
    "Skinner",
    "Wilkinson",
    "Kirby",
    "Cameron",
    "Bridges",
    "Anthony",
    "Richard",
    "Kirk",
    "Bruce",
    "Singleton",
    "Mathis",
    "Bradford",
    "Boone",
    "Abbott",
    "Charles",
    "Allison",
    "Sweeney",
    "Atkinson",
    "Horn",
    "Jefferson",
    "Rosales",
    "York",
    "Christian",
    "Phelps",
    "Farrell",
    "Castaneda",
    "Nash",
    "Dickerson",
    "Bond",
    "Wyatt",
    "Foley",
    "Chase",
    "Gates",
    "Vincent",
    "Mathews",
    "Hodge",
    "Garrison",
    "Trevino",
    "Villarreal",
    "Heath",
    "Dalton",
    "Valencia",
    "Callahan",
    "Hensley",
    "Atkins",
    "Huffman",
    "Roy",
    "Boyer",
    "Shields",
    "Lin",
    "Hancock",
    "Grimes",
    "Glenn",
    "Cline",
    "Delacruz",
    "Camacho",
    "Dillon",
    "Parrish",
    "Oneill",
    "Melton",
    "Booth",
    "Kane",
    "Berg",
    "Harrell",
    "Pitts",
    "Savage",
    "Wiggins",
    "Brennan",
    "Salas",
    "Marks",
    "Russo",
    "Sawyer",
    "Baxter",
    "Golden",
    "Hutchinson",
    "Liu",
    "Walter",
    "Mcdowell",
    "Wiley",
    "Rich",
    "Humphrey",
    "Johns",
    "Koch",
    "Suarez",
    "Hobbs",
    "Beard",
    "Gilmore",
    "Ibarra",
    "Keith",
    "Macias",
    "Khan",
    "Andrade",
    "Ware",
    "Stephenson",
    "Henson",
    "Wilkerson",
    "Dyer",
    "Mcclure",
    "Blackwell",
    "Mercado",
    "Tanner",
    "Eaton",
    "Clay",
    "Barron",
    "Beasley",
    "Oneal",
    "Preston",
    "Small",
    "Wu",
    "Zamora",
    "Macdonald",
    "Vance",
    "Snow",
    "Mcclain",
    "Stafford",
    "Orozco",
    "Barry",
    "English",
    "Shannon",
    "Kline",
    "Jacobson",
    "Woodard",
    "Huang",
    "Kemp",
    "Mosley",
    "Prince",
    "Merritt",
    "Hurst",
    "Villanueva",
    "Roach",
    "Nolan",
    "Lam",
    "Yoder",
    "Mccullough",
    "Lester",
    "Santana",
    "Valenzuela",
    "Winters",
    "Barrera",
    "Leach",
    "Orr",
    "Berger",
    "Mckee",
    "Strong",
    "Conway",
    "Stein",
    "Whitehead",
    "Bullock",
    "Escobar",
    "Knox",
    "Meadows",
    "Solomon",
    "Velez",
    "Odonnell",
    "Kerr",
    "Stout",
    "Blankenship",
    "Browning",
    "Kent",
    "Lozano",
    "Bartlett",
    "Pruitt",
    "Buck",
    "Barr",
    "Gaines",
    "Durham",
    "Gentry",
    "Mcintyre",
    "Sloan"
  ];
  const customers = [
    "IntApp",
    "Google",
    "Microsoft",
    "F5",
    "Boston Dynamics",
    "Intel",
    "Reddit"
  ];
  const opportunities = [
    "Web-app new functionality",
    "Global platform for webinars",
    "Redesign system design",
    "Unit/UI/E2E tests",
    "Clear the tech due",
    "Frontend features development",
    "Database redesign"
  ];
  const positions = [
    "Senior Android Developer",
    "Senior Frontend Developer (React, Angular)",
    "iOS Mobile SDE",
    "Q&A Engineer",
    "Data Scientist",
    "System Analyst",
    "Senior Backend Developer (NodeJS)"
  ];

  const seniorities = [
    "Senior Developer",
    "Middle Developer",
    "Junior Developer",
    "Senior Frontend Developer",
    "Middle Frontend Developer",
    "Junior Frontend Developer",
    "Senior Backend Developer",
    "Middle Backend Developer",
    "Junior Backend Developer"
  ];

  const techStacks = [
    "Node JS",
    "ASP.NET",
    ".NET",
    "React",
    "Angular",
    "Vue.js",
    "Linux",
    "MySql"
  ];

  let _candidates: ICandidate[] = [];
  let _customers: ICustomer[] = generateCustomers();
  let rnd = randomNumber(4, 7);
  for (let i = 0; i < rnd; i++) {
    generateCandidate();
  }
  return { candidates: _candidates, customers: _customers };
  function getAvatar(name: string) {
    return "https://api.adorable.io/avatars/50/" + name + "@adorable.png";
  }
  function generateCustomers(): ICustomer[] {
    let result: ICustomer[] = [];
    for (let customer of customers) {
      result.push({ id: genId(), name: customer, opps: generateOpps() });
    }
    return result;
  }
  function generateOpps(): IOpportunity[] {
    let result: IOpportunity[] = [];
    for (let opportunity of getRandom(opportunities, randomNumber(1, 4))) {
      result.push({
        id: genId(),
        title: opportunity,
        due: randomDue(),
        positions: generatePositions()
      });
    }
    return result;
  }
  function generatePositions(): IPosition[] {
    let result: IPosition[] = [];
    for (let position of getRandom(positions, randomNumber(1, 3))) {
      for (let i = 0; i < randomNumber(1, 6); i++) {
        let candidate = Math.random() < 0.6 ? generateCandidate() : undefined;
        result.push({ id: genId(), title: position, candidate });
      }
    }
    return result;
  }
  function generateCandidate(): ICandidate {
    const candidateName =
      firstNames[randomNumber(0, firstNames.length - 1)] +
      " " +
      lastNames[randomNumber(0, lastNames.length - 1)];
    const candidate: ICandidate = {
      id: genId(),
      name: candidateName,
      avatar: getAvatar(encodeURI(candidateName)),
      seniority: seniorities[randomNumber(0, seniorities.length - 1)],
      techStack: techStacks[randomNumber(0, techStacks.length - 1)]
    };
    _candidates.push(candidate);
    return candidate;
  }
  function getRandom(arr: Array<string>, n: number): string[] {
    var result = new Array(n),
      len = arr.length,
      taken = new Array(len);
    if (n > len)
      throw new RangeError("getRandom: more elements taken than available");
    while (n--) {
      var x = Math.floor(Math.random() * len);
      result[n] = arr[x in taken ? taken[x] : x];
      taken[x] = --len in taken ? taken[len] : len;
    }
    return result;
  }
  function randomNumber(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }
  function randomDue(): Date {
    return new Date(2020, randomNumber(1, 12), randomNumber(1, 28));
  }
  function genId(): string {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {
      var r = (Math.random() * 16) | 0,
        v = c === "x" ? r : (r & 0x3) | 0x8;
      return v.toString(16);
    });
  }
};

const data = generateFakeData();
export const fakeData = data.customers;
export const fakeCandidates = data.candidates;
/* export const fakeData: ICustomer[] = [
  {
    id: genId(),
    name: "Google",
    opps: [
      {
        id: genId(),
        title: "SkyNet",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      },
      {
        id: genId(),
        title: "Test1",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      }
    ]
  },
  {
    id: genId(),
    name: "Yandex",
    opps: [
      {
        id: genId(),
        title: "Cheburashka",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      }
    ]
  },
  {
    id: genId(),
    name: "IntApp",
    opps: [
      {
        id: genId(),
        title: "Test2",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      },
      {
        id: genId(),
        title: "Test3",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      }
    ]
  },
  {
    id: genId(),
    name: "Reddit",
    opps: [
      {
        id: genId(),
        title: "Test4",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      },
      {
        id: genId(),
        title: "Test5",
        due: new Date(2020, 1, 12),
        positions: [
          {
            id: genId(),
            title: "Junior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjQ5OTc4ODk1/chuck-norris-15720761-1-402.jpg",
              name: "Chuck Norris"
            }
          },
          {
            id: genId(),
            title: "Senior developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MTIyMTE4MTU5/arnold-schwarzenegger-9476355-1-402.jpg",
              name: "Arnold Schwarzenegger"
            }
          },
          {
            id: genId(),
            title: "Middle developer",
            candidate: {
              id: genId(),
              avatar:
                "https://www.biography.com/.image/t_share/MTE4MDAzNDEwNjkyNzY5Mjk0/sylvester-stallone-9491745-1-402.jpg",
              name: "Sylvester Stallone"
            }
          },
          {
            id: genId(),
            title: "Android developer"
          },
          {
            id: genId(),
            title: "Senior Android Developer"
          }
        ]
      }
    ]
  }
];

export const fakeCandidates: ICandidate[] = [
  {
    id: genId(),
    name: "Jason Statham",
    avatar:
      "https://www.biography.com/.image/t_share/MTUzMzQzOTkxMDAwMDgxNzA2/jason-statham-attends-the-press-conference-of-director-f-gary-grays-film-the-fate-of-the-furious-on-march-23-2017-in-beijing-china-photo-by-vcg_vcg-via-getty-images-square.jpg"
  },
  {
    id: genId(),
    name: "Dwayne Johnson",
    avatar:
      "https://www.biography.com/.image/t_share/MTE5NDg0MDU1MjM5ODg2MzUx/dwayne-johnson-11818916-1-402.jpg"
  }
]; */
